import ts from 'typescript'
import { describe, expect, it } from 'vitest'
import type { ConstructionSuccess } from '../../../tools/generator/src/types.js'
import { layoutModuleFile, puzzleModuleFile, registrySnippet, tsString } from './exportSource'
import { prepareFinalPuzzle } from './finalPuzzle'

// CAT across crossing TIE down at the T, with a stray-order cell map so
// the export's own ordering (not insertion order) is what's tested.
const construction: ConstructionSuccess = {
  ok: true,
  placedAnswers: [
    { word: 'TIE', direction: 'down', start: { x: 2, y: 0 } },
    { word: 'CAT', direction: 'across', start: { x: 0, y: 0 } },
  ],
  cells: { r2c2: 'E', r0c1: 'A', r0c0: 'C', r1c2: 'I', r0c2: 'T' },
  positions: {
    r2c2: { x: 2, y: 2 },
    r0c1: { x: 1, y: 0 },
    r0c0: { x: 0, y: 0 },
    r1c2: { x: 2, y: 1 },
    r0c2: { x: 2, y: 0 },
  },
  width: 3,
  height: 3,
  attemptsUsed: 1,
}

function exportFor(clue: string) {
  const { puzzle, layout, ready } = prepareFinalPuzzle(construction, { id: 'cats', clue })
  if (!ready || !puzzle || !layout) throw new Error('expected an export-ready pair')
  return { puzzleFile: puzzleModuleFile(puzzle, layout), layoutFile: layoutModuleFile(layout) }
}

// Typechecks generated modules as if saved at their real repo paths,
// without writing anything: an in-memory overlay on the real filesystem,
// so their imports resolve against the actual production types/constants.
function typecheck(files: { path: string; source: string }[]): string[] {
  const root = decodeURIComponent(new URL('../../../', import.meta.url).pathname)
  const overlay = new Map(files.map((file) => [`${root}${file.path}`, file.source]))
  const options: ts.CompilerOptions = {
    target: ts.ScriptTarget.ES2023,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    strict: true,
    noEmit: true,
    skipLibCheck: true,
    verbatimModuleSyntax: true,
    types: [],
  }
  const host = ts.createCompilerHost(options)
  const { fileExists, readFile, getSourceFile } = host
  host.fileExists = (name) => overlay.has(name) || fileExists.call(host, name)
  host.readFile = (name) => overlay.get(name) ?? readFile.call(host, name)
  host.getSourceFile = (name, version, onError, shouldCreate) => {
    const text = overlay.get(name)
    return text !== undefined
      ? ts.createSourceFile(name, text, version)
      : getSourceFile.call(host, name, version, onError, shouldCreate)
  }
  const program = ts.createProgram([...overlay.keys()], options, host)
  return ts
    .getPreEmitDiagnostics(program)
    .map((diagnostic) => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'))
}

describe('Final Puzzle export source', () => {
  it('names the two modules after the puzzle id, at their production paths', () => {
    const { puzzleFile, layoutFile } = exportFor('Cats')
    expect(puzzleFile).toMatchObject({ path: 'src/data/catsPuzzle.ts', filename: 'catsPuzzle.ts' })
    expect(layoutFile).toMatchObject({ path: 'src/layout/catsPuzzleLayout.ts', filename: 'catsPuzzleLayout.ts' })
  })

  it('emits the puzzle module in the hand-authored format', () => {
    expect(exportFor('Cats').puzzleFile.source).toBe(
      [
        `import { DEFAULT_REVEAL_BUDGET } from '../core/letterCosts'`,
        `import type { PuzzleDefinition } from '../core/types'`,
        ``,
        `// Generated by the ClueCross Workshop from an approved candidate. See`,
        `// layout/catsPuzzleLayout.ts for cell positions.`,
        `export const catsPuzzle: PuzzleDefinition = {`,
        `  id: 'cats',`,
        `  clue: 'Cats',`,
        `  unlockBudget: DEFAULT_REVEAL_BUDGET,`,
        `  cells: {`,
        `    r0c0: { id: 'r0c0', correctLetter: 'C' }, r0c1: { id: 'r0c1', correctLetter: 'A' }, r0c2: { id: 'r0c2', correctLetter: 'T' },`,
        `    r1c2: { id: 'r1c2', correctLetter: 'I' },`,
        `    r2c2: { id: 'r2c2', correctLetter: 'E' },`,
        `  },`,
        `  entries: [`,
        `    { id: 'cat', cellIds: ['r0c0', 'r0c1', 'r0c2'] },`,
        `    { id: 'tie', cellIds: ['r0c2', 'r1c2', 'r2c2'] },`,
        `  ],`,
        `}`,
        ``,
      ].join('\n'),
    )
  })

  it('emits the layout module in the hand-authored format', () => {
    expect(exportFor('Cats').layoutFile.source).toBe(
      [
        `import type { LayoutDefinition } from './types'`,
        ``,
        `// Generated by the ClueCross Workshop: x = column, y = row.`,
        `export const catsPuzzleLayout: LayoutDefinition = {`,
        `  id: 'cats-grid',`,
        `  puzzleId: 'cats',`,
        `  cellPositions: {`,
        `    r0c0: { x: 0, y: 0 }, r0c1: { x: 1, y: 0 }, r0c2: { x: 2, y: 0 },`,
        `    r1c2: { x: 2, y: 1 },`,
        `    r2c2: { x: 2, y: 2 },`,
        `  },`,
        `  navigationOrder: [`,
        `    'r0c0', 'r0c1', 'r0c2',`,
        `    'r1c2',`,
        `    'r2c2',`,
        `  ],`,
        `}`,
        ``,
      ].join('\n'),
    )
  })

  it('is deterministic across repeated exports', () => {
    expect(exportFor('Cats')).toEqual(exportFor('Cats'))
  })

  it('escapes clue text safely', () => {
    expect(tsString(`It's a "cat"`)).toBe(`'It\\'s a "cat"'`)
    expect(tsString('back\\slash')).toBe(`'back\\\\slash'`)
    expect(tsString('line\nbreak\ttab')).toBe(`'line\\nbreak\\ttab'`)
    expect(tsString('\\"')).toBe(`'\\\\"'`)
    const clue = `Cat's "meow" \\ ${'${x}'} ’ — café`
    const { puzzleFile } = exportFor(clue)
    // Evaluating the emitted literal gives back the exact clue.
    const literal = puzzleFile.source.match(/^ {2}clue: (.*),$/m)![1]
    expect(new Function(`return ${literal}`)()).toBe(clue)
  })

  it('generates modules that typecheck against the real production types, even with a tricky clue', () => {
    const { puzzleFile, layoutFile } = exportFor(`Cat's "meow" \\ \n end`)
    expect(typecheck([puzzleFile, layoutFile])).toEqual([])
  })

  it('the typecheck harness does catch invalid output', () => {
    const { puzzleFile } = exportFor('Cats')
    const broken = { ...puzzleFile, source: puzzleFile.source.replace('unlockBudget: DEFAULT_REVEAL_BUDGET,', '') }
    expect(typecheck([broken]).join('\n')).toMatch(/unlockBudget/)
  })

  it('builds a registry snippet matching puzzleIds.ts and archivePuzzles.ts', () => {
    expect(registrySnippet('cats')).toBe(
      [
        `// src/data/puzzleIds.ts — add the id to PUZZLE_IDS:`,
        `'cats',`,
        ``,
        `// src/data/archivePuzzles.ts — imports:`,
        `import { catsPuzzleLayout } from '../layout/catsPuzzleLayout'`,
        `import { catsPuzzle } from './catsPuzzle'`,
        ``,
        `// src/data/archivePuzzles.ts — PUZZLES entry:`,
        `cats: { puzzle: catsPuzzle, layout: catsPuzzleLayout },`,
        ``,
      ].join('\n'),
    )
  })

  it('leaves scheduling out of the registry snippet', () => {
    const snippet = registrySnippet('cats')
    expect(snippet).not.toMatch(/SCHEDULE|offsetDays|schedul|today|bump/i)
  })
})
