// Source text for a Final Puzzle export: the same two TypeScript modules
// authors write by hand today (src/data/<id>Puzzle.ts and
// src/layout/<id>PuzzleLayout.ts), plus a copyable archivePuzzles.ts
// registry snippet. Pure and deterministic: the same pair always yields
// byte-identical text. Callers export only a pair that passed Final
// Puzzle validation (so `id` is a safe slug); string values are still
// always emitted as escaped literals, never interpolated raw.

import type { Cell, CellId, Entry, PuzzleDefinition } from '../../../src/core/types'
import { deriveEntryDirection } from '../../../src/layout/entryDirection'
import type { LayoutDefinition, Position } from '../../../src/layout/types'

export interface ExportFile {
  /** Repo-relative destination, e.g. src/data/dogsPuzzle.ts. */
  path: string
  /** Download filename, e.g. dogsPuzzle.ts. */
  filename: string
  source: string
}

const CELLS_PER_LINE = 4
const IDS_PER_LINE = 8

/** A single-quoted TypeScript string literal for any text (quotes, backslashes, control characters). */
export function tsString(value: string): string {
  const escaped = JSON.stringify(value)
    .slice(1, -1)
    .replace(/\\"/g, '"')
    .replace(/'/g, "\\'")
  return `'${escaped}'`
}

export function puzzleExportName(id: string): string {
  return `${id}Puzzle`
}

export function layoutExportName(id: string): string {
  return `${id}PuzzleLayout`
}

// Row-major, matching navigationOrder and the hand-authored modules.
function rowMajor(cellIds: CellId[], positions: Record<CellId, Position>): CellId[] {
  return [...cellIds].sort((a, b) => positions[a].y - positions[b].y || positions[a].x - positions[b].x)
}

// One source line per board row, wrapped to `perLine` items.
function rowLines(cellIds: CellId[], positions: Record<CellId, Position>, perLine: number, format: (id: CellId) => string): string[] {
  const lines: string[] = []
  let row: CellId[] = []
  const flush = () => {
    for (let i = 0; i < row.length; i += perLine) {
      lines.push(`    ${row.slice(i, i + perLine).map(format).join(', ')},`)
    }
    row = []
  }
  for (const cellId of cellIds) {
    if (row.length > 0 && positions[row[0]].y !== positions[cellId].y) flush()
    row.push(cellId)
  }
  flush()
  return lines
}

// Across answers first, then down, each by start row then column; each
// entry keeps its start-to-end cell order.
function orderedEntries(entries: Entry[], layout: LayoutDefinition): Entry[] {
  const rank = (entry: Entry) => (deriveEntryDirection(entry, layout) === 'down' ? 1 : 0)
  const start = (entry: Entry) => layout.cellPositions[entry.cellIds[0]]
  return [...entries].sort(
    (a, b) => rank(a) - rank(b) || start(a).y - start(b).y || start(a).x - start(b).x,
  )
}

function cellLiteral(cell: Cell): string {
  return `${propertyKey(cell.id)}: { id: ${tsString(cell.id)}, correctLetter: ${tsString(cell.correctLetter)} }`
}

function propertyKey(cellId: CellId): string {
  return /^[A-Za-z_$][\w$]*$/.test(cellId) ? cellId : tsString(cellId)
}

export function puzzleModuleFile(puzzle: PuzzleDefinition, layout: LayoutDefinition): ExportFile {
  const cellIds = rowMajor(Object.keys(puzzle.cells), layout.cellPositions)
  const cellLines = rowLines(cellIds, layout.cellPositions, CELLS_PER_LINE, (id) => cellLiteral(puzzle.cells[id]))
  const entryLines = orderedEntries(puzzle.entries, layout).map(
    (entry) => `    { id: ${tsString(entry.id)}, cellIds: [${entry.cellIds.map(tsString).join(', ')}] },`,
  )
  const source = [
    `import { DEFAULT_REVEAL_BUDGET } from '../core/letterCosts'`,
    `import type { PuzzleDefinition } from '../core/types'`,
    ``,
    `// Generated by the ClueCross Workshop from an approved candidate. See`,
    `// layout/${layoutExportName(puzzle.id)}.ts for cell positions.`,
    `export const ${puzzleExportName(puzzle.id)}: PuzzleDefinition = {`,
    `  id: ${tsString(puzzle.id)},`,
    `  clue: ${tsString(puzzle.clue)},`,
    `  unlockBudget: DEFAULT_REVEAL_BUDGET,`,
    `  cells: {`,
    ...cellLines,
    `  },`,
    `  entries: [`,
    ...entryLines,
    `  ],`,
    `}`,
    ``,
  ].join('\n')
  const filename = `${puzzleExportName(puzzle.id)}.ts`
  return { path: `src/data/${filename}`, filename, source }
}

export function layoutModuleFile(layout: LayoutDefinition): ExportFile {
  const positions = layout.cellPositions
  const cellIds = rowMajor(Object.keys(positions), positions)
  const positionLines = rowLines(cellIds, positions, CELLS_PER_LINE, (id) => `${propertyKey(id)}: { x: ${positions[id].x}, y: ${positions[id].y} }`)
  const orderLines = rowLines(layout.navigationOrder, positions, IDS_PER_LINE, tsString)
  const source = [
    `import type { LayoutDefinition } from './types'`,
    ``,
    `// Generated by the ClueCross Workshop: x = column, y = row.`,
    `export const ${layoutExportName(layout.puzzleId)}: LayoutDefinition = {`,
    `  id: ${tsString(layout.id)},`,
    `  puzzleId: ${tsString(layout.puzzleId)},`,
    `  cellPositions: {`,
    ...positionLines,
    `  },`,
    `  navigationOrder: [`,
    ...orderLines,
    `  ],`,
    `}`,
    ``,
  ].join('\n')
  const filename = `${layoutExportName(layout.puzzleId)}.ts`
  return { path: `src/layout/${filename}`, filename, source }
}

/**
 * Developer integration reference only — the Workshop never edits these
 * files. Mirrors the current puzzleIds.ts / archivePuzzles.ts registry
 * structure. Deliberately no schedule row: publishing and calendar
 * scheduling belong to a separate workflow.
 */
export function registrySnippet(id: string): string {
  const puzzleName = puzzleExportName(id)
  const layoutName = layoutExportName(id)
  return [
    `// src/data/puzzleIds.ts — add the id to PUZZLE_IDS:`,
    `${tsString(id)},`,
    ``,
    `// src/data/archivePuzzles.ts — imports:`,
    `import { ${layoutName} } from '../layout/${layoutName}'`,
    `import { ${puzzleName} } from './${puzzleName}'`,
    ``,
    `// src/data/archivePuzzles.ts — PUZZLES entry:`,
    `${id}: { puzzle: ${puzzleName}, layout: ${layoutName} },`,
    ``,
  ].join('\n')
}
